# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic_graph.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'semantic_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14semantic_graph.proto\"i\n\x08Location\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x11\n\tstartLine\x18\x02 \x01(\x05\x12\x16\n\x0estartCharacter\x18\x03 \x01(\x05\x12\x0f\n\x07\x65ndLine\x18\x04 \x01(\x05\x12\x14\n\x0c\x65ndCharacter\x18\x05 \x01(\x05\"=\n\x04\x45\x64ge\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x1b\n\x08location\x18\x03 \x01(\x0b\x32\t.Location\"\xd0\x01\n\tGraphNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x1b\n\x08location\x18\x03 \x01(\x0b\x32\t.Location\x12.\n\nproperties\x18\x04 \x03(\x0b\x32\x1a.GraphNode.PropertiesEntry\x12\x13\n\x0b\x64isplayName\x18\x05 \x01(\t\x12\x14\n\x05\x65\x64ges\x18\x06 \x03(\x0b\x32\x05.Edge\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x11SemanticGraphFile\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x19\n\x05nodes\x18\x02 \x03(\x0b\x32\n.GraphNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPHNODE_PROPERTIESENTRY']._loaded_options = None
  _globals['_GRAPHNODE_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_LOCATION']._serialized_start=24
  _globals['_LOCATION']._serialized_end=129
  _globals['_EDGE']._serialized_start=131
  _globals['_EDGE']._serialized_end=192
  _globals['_GRAPHNODE']._serialized_start=195
  _globals['_GRAPHNODE']._serialized_end=403
  _globals['_GRAPHNODE_PROPERTIESENTRY']._serialized_start=354
  _globals['_GRAPHNODE_PROPERTIESENTRY']._serialized_end=403
  _globals['_SEMANTICGRAPHFILE']._serialized_start=405
  _globals['_SEMANTICGRAPHFILE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
